### ISSUE TITLE
No results No errors

### ISSUE THREAD

**Issue by kyunam** [logstash-plugins/logstash-input-jdbc#6]
I only see "Logstash startup completed" then nothing happens whether I use sql_last_start or not.
I use Logstash 1.5.0 and the configuration is,
input {
jdbc {
jdbc_driver_library => '/Users/someWhere/sqljdbc4.jar'
jdbc_driver_class => 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
jdbc_connection_string => 'jdbc:sqlserver://myServer:1433;databaseName=myDB'
jdbc_user => 'aUser'
jdbc_password => 'aPassword'
statement => 'SELECT * FROM LOGSTASH_POINT where CREATED_DATE > :sql_last_start'
#parameters => { "sql_last_start" => "2014-01-01" }
jdbc_validate_connection => true
schedule => "* * * * *"
}
}
output {
stdout { codec => rubydebug }
}

Any help is appreciated.

**Comment by talevy** [comment]
do you see any errors? it looks like the prototype had a bug where the scheduler library used was not being loaded at runtime, and instead only during development.

would you mind updating the plugin to the latest release I just pushed?

```
$ bin/plugin update logstash-input-jdbc
```

**Comment by kyunam** [comment]
i tried the latest but still the same.
If I removed scheduler, I see "Logstash startup completed Logstash shutdown completed" immediately.

**Comment by talevy** [comment]
following up, were you able to resolve this issue?

**Comment by kyunam** [comment]
Nop. I couldn't.

**Comment by talevy** [comment]
I will add some debug statements to further inform on the progress. but it may very well be that no results were returned from the statement.

**Comment by talevy** [comment]
would you mind trying with the latest code on master?

**Comment by talevy** [comment]
@lathabudi I am familiar with this issue. This should be cleared up in the latest release. have you updated since the opening of this issue?

Which database are you using, and what type is staging_timestamp?

**Comment by lathabudi** [comment]
Yes, I updated the plugin. I think I was able to get around the issue by adding last_run_metadata_path parameter. I am using oracle database and staging_timestamp is of type timestamp. I am able to get the data from database now. But I had one question, if you have a field similat to sql_last_start that can be read dynamically while the scheduler is still running, that would be beneficial. So, when the scheduler wakes up to run the sql query, it will grab only the records that were updated after the previous run. Thanks!

**Comment by talevy** [comment]
@lathabudi that field `:sql_last_start` gets updated after every query run. so when you schedule, and run the query again. it will be updated. is that what you mean? is that not what it is doing?

**Comment by lathabudi** [comment]
@talevy I think it is not doing that. As mentioned in the documentation link below it is only updating when the logstash session is terminated manually (or shutdown). If I leave the process running in the background and the file was left untouched.

"Upon shutting down, this file will be updated with the current value of sql_last_start."
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#_state

**Comment by talevy** [comment]
Ah, the file is left untouched, this is true (during the run) but the value itself is updated. it is only updated on disk upon shutdown. I can update the docs to make this more apparent

**Comment by talevy** [comment]
I suppose it wouldn't hurt to update it on disk in between runs as well. I can file a ticket for this

**Comment by lathabudi** [comment]
@talevy That would be really nice if we can bank on that variable for the last run time. Thanks,

**Comment by talevy** [comment]
currently, you can as well! it is just updated in memory, not on disk until logstash shuts down.

**Comment by lathabudi** [comment]
@talevy  But with the combination of :sql_last_start parameter and last_run_metadata_path option enabled, it doesn't seem to work.

**Comment by talevy** [comment]
I will look into this

**Comment by ScottBeeson** [comment]
I'm still having this problem.  I was able to create and populate an index with `SELECT * FROM tableName` but when I added `WHERE datetime > :sql_last_start` nothing happens.  I get no data or errors.

**Comment by suyograo** [comment]
Please open a new issue if this happens again
